using System.Collections.Generic;

namespace Laa.Monogame.Client.Networking;

internal static class ServerMessageCatalog
{
    private static readonly IReadOnlyDictionary<byte, string> Messages = new Dictionary<byte, string>
    {
        [0] = "Acción completada.",
        [1] = "La acción no pudo ejecutarse.",
        [2] = "Tu raza no puede usar ese objeto.",
        [3] = "Tu clase no puede usar ese objeto.",
        [4] = "Esta casilla pertenece a otro tipo de objeto.",
        [5] = "Tus manos están ocupadas y la bolsa llena.",
        [6] = "No puedes atacar con tu arma rota.",
        [7] = "No tienes la pericia Ambidextría.",
        [8] = "Arruinaste la gema.",
        [9] = "Estás muerto, primero necesitas ser resucitado.",
        [10] = "Necesitas un espacio libre en tu bolso.",
        [11] = "Estás paralizado.",
        [12] = "Ese objeto se coloca en la otra mano.",
        [13] = "No tienes nada para afilar en tus manos.",
        [14] = "Coloca el arco o ballesta en tu mano derecha.",
        [15] = "Coloca el objeto a reparar en tu mano derecha.",
        [16] = "Ese objeto no es reparable.",
        [17] = "No puedes repararlo mejor de lo que está.",
        [18] = "Este no es buen lugar para la fogata.",
        [19] = "Necesitas cinco leños para preparar la fogata.",
        [20] = "Busca un lugar protegido de la lluvia.",
        [21] = "Debes estar frente a una veta de mineral.",
        [22] = "Aquí no hay peces.",
        [23] = "Tienes que estar frente a un árbol para talarlo.",
        [24] = "Pon una gema sin tallar en tu mano izquierda.",
        [25] = "Debes estar frente a una fundición.",
        [26] = "Sólo un herrero o un minero funden metal.",
        [27] = "Necesitas 4 minerales para un lingote.",
        [28] = "Necesitas 8 minerales para un lingote de plata.",
        [29] = "Necesitas 16 minerales para un lingote de oro.",
        [30] = "Sólo un herbalista puede crear pócimas.",
        [31] = "Debes estar frente a una mesa de sastre.",
        [32] = "Debes estar frente a un telar.",
        [33] = "No tienes la pericia Sastrería.",
        [34] = "Necesitas al menos 4 fibras.",
        [35] = "No tienes la pericia Herrería.",
        [36] = "Sólo un sastre puede fabricar tela.",
        [37] = "No tienes la pericia Carpintería.",
        [38] = "Desconoces los secretos de la Alquimia.",
        [39] = "No tienes la pericia para escribir magia.",
        [40] = "Debes estar frente a un yunque.",
        [41] = "Pon un pergamino en blanco en tu mano izquierda.",
        [42] = "Calmaste tu sed.",
        [43] = "Calmaste tu hambre.",
        [44] = "Bebes la pócima mágica.",
        [45] = "Echaste el brebaje venenoso.",
        [46] = "No tienes hambre.",
        [47] = "No tienes sed.",
        [48] = "No tienes heridas.",
        [49] = "Tu nivel de maná está al máximo.",
        [50] = "Esta pócima no es para tu clase.",
        [51] = "No necesitas usar vendas.",
        [52] = "Un obstáculo del terreno impide atacar al objetivo.",
        [53] = "Coloca un arma en tus manos para atacar.",
        [54] = "Tu munición no corresponde con tu arma.",
        [55] = "Debes apuntar primero.",
        [56] = "Fallaste.",
        [57] = "Tienes que acercarte, estás muy lejos.",
        [58] = "El objetivo está protegido.",
        [59] = "Debes apuntar a un avatar.",
        [60] = "Aquí no hay espacio para dejar más cosas.",
        [61] = "Ya no tienes espacio en tu inventario.",
        [62] = "Desocupa tu mano derecha.",
        [63] = "Este no es buen lugar para la trampa.",
        [64] = "No tienes suficiente nivel para fabricar con esta herramienta.",
        [65] = "Necesitas la pericia Sastrería para curtir pieles.",
        [66] = "Debes estar frente a una tina de curtido.",
        [67] = "Necesitas al menos 4 pieles.",
        [68] = "No tienes los materiales necesarios.",
        [69] = "Aquí no hay ingredientes de pócimas.",
        [70] = "No estás envenenado.",
        [71] = "Ira Berserker necesita más puntos de salud.",
        [72] = "Ese objeto no puede envenenarse.",
        [73] = "Pon en tu mano derecha algo para envenenar.",
        [74] = "No eres bardo.",
        [75] = "Debes estar frente a un estudio de magia.",
        [76] = "Debes estar frente a un estudio de alquimia.",
        [77] = "Necesitas más tinta mágica.",
        [78] = "La venta se concretó.",
        [79] = "La compra se concretó.",
        [80] = "Elige un objeto del inventario.",
        [81] = "Rechazó tu oferta.",
        [82] = "Mejor no intentes vender eso.",
        [83] = "Acércate y señala a un comerciante.",
        [84] = "Ese objetivo no es un comerciante.",
        [86] = "No compro ni vendo ese tipo de objetos.",
        [87] = "No es lo acordado, no hay trato.",
        [88] = "Tu maná debe estar al máximo.",
        [89] = "Debes estar frente a un taller de carpintería.",
        [90] = "No conoces o no puedes escribir ese conjuro.",
        [91] = "No tienes suficiente maná.",
        [92] = "No sabes hacer magia.",
        [93] = "Te falta nivel para leer ese pergamino.",
        [94] = "Le quitaste casi todos los puntos de salud.",
        [95] = "Este hechizo sólo afecta a avatares.",
        [96] = "Tu hechizo fue vencido por resistencia mágica.",
        [97] = "Un obstáculo impide que el conjuro pase.",
        [98] = "No lograste maldecir sus pertenencias.",
        [99] = "Está protegido contra hechizos malvados.",
        [100] = "No tiene vida que puedas drenar.",
        [101] = "Ese objeto ya está identificado.",
        [102] = "No se puede conjurar el monstruo en ese lugar.",
        [103] = "Coloca una gema tallada en tu mano derecha.",
        [104] = "Necesitas una amatista, aguamarina, esmeralda o un brillante.",
        [105] = "Necesitas un topacio, zafiro, rubí o sol oscuro.",
        [106] = "Esta gema no es adecuada para el conjuro.",
        [107] = "Necesitas un objeto valioso en tu mano derecha.",
        [108] = "Necesitas una gema entre 50% y 100% de calidad.",
        [109] = "Ya conoces el hechizo del pergamino.",
        [110] = "Ya no te queda maná.",
        [111] = "Falló el hechizo: tu varita mágica se agotó.",
        [112] = "Este hechizo no actúa sobre muertos.",
        [113] = "¡Han maldecido tus pertenencias!",
        [114] = "Decides no lanzar el hechizo contra ese objetivo.",
        [115] = "Su amuleto lo protegió de la maldición.",
        [116] = "No conoces ese conjuro.",
        [117] = "Necesitas más nivel para usar ese objeto.",
        [118] = "El Brillante no afecta armaduras.",
        [119] = "Debes estar frente a un taller de joyería.",
        [120] = "No tienes la pericia Ocultarse.",
        [121] = "No pudiste ocultarte.",
        [122] = "No tienes la pericia Ira Berserker.",
        [123] = "No tienes la pericia Zoomorfismo.",
        [124] = "Desequipa tus objetos para usar Zoomorfismo.",
        [125] = "Ya estás en forma de animal.",
        [126] = "Zoomorfismo necesita más maná.",
        [127] = "Necesitas más maná para usar instrumentos.",
        [128] = "¡Tu moral de combate se elevó!",
        [129] = "Para modo agresivo escribe: /agr.",
        [130] = "Ese objeto no se puede hechizar.",
        [131] = "Necesitas una calidad mayor para bendecir.",
        [132] = "Ese objeto ya está hechizado.",
        [133] = "Sólo puedes atacarle si se vuelve agresivo.",
        [134] = "No puedes atacarle porque no lo ves.",
        [135] = "Su amuleto lo oculta.",
        [136] = "No puedes moverte ni pararte allí.",
        [140] = "No puedes agregar otro miembro al grupo.",
        [141] = "Su grupo ya está completo.",
        [142] = "Invitaste al avatar a tu grupo.",
        [143] = "Ese avatar ya está en tu grupo.",
        [150] = "Esta comida está cruda, hay que cocinarla.",
        [151] = "No tienes el nivel mínimo necesario.",
        [152] = "La resurrección es para los muertos.",
        [153] = "Es invulnerable a tu hechizo.",
        [154] = "No necesitas usar la pócima.",
        [155] = "Ese monstruo está bajo tus órdenes.",
        [156] = "Necesitas tener equipado el anillo del control.",
        [157] = "Debes apuntar a un monstruo.",
        [160] = "Has creado un nuevo clan. Ahora eres el líder.",
        [161] = "Ese avatar no pertenece a ningún clan.",
        [162] = "No puedes formar otro clan; ya existen demasiados.",
        [163] = "Ese avatar ya tiene un clan.",
        [164] = "Ese avatar no pertenece a tu clan.",
        [165] = "Acción reservada a líderes de clan.",
        [166] = "No perteneces a un clan.",
        [167] = "Los miembros de un clan no pueden atacarse entre sí.",
        [168] = "Ya existe un nombre muy parecido.",
        [169] = "Pon 30 monedas de plata en tu mano derecha.",
        [170] = "El castillo no tiene esa cantidad de dinero.",
        [171] = "Esa mejora ya fue realizada.",
        [172] = "Has mejorado las defensas de tu castillo.",
        [173] = "Tu baúl mágico está lleno.",
        [174] = "Elige un objeto de tu baúl.",
        [175] = "Elige un objeto de la bolsa.",
        [194] = "No tienes privilegio para usar ese comando.",
        [195] = "Desocupa la primera casilla de tu inventario.",
        [196] = "La opción de múltiples sesiones no está activa.",
        [197] = "Necesitas mayor nivel administrativo.",
        [198] = "No existe una catedral cerca de esta zona.",
        [199] = "Comando administrativo ejecutado."
    };

    public static string Resolve(byte code)
    {
        if (code >= 200 && code <= 229)
        {
            return $"Hechizo ejecutado correctamente (código {code}).";
        }

        if (Messages.TryGetValue(code, out var text))
        {
            return text;
        }

        return $"Mensaje del servidor #{code}";
    }
}
